/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/schema.rs:6
-- bootstrap

CREATE SCHEMA mdm;
CREATE SCHEMA mdm_out;
CREATE SCHEMA mdm_steward;
CREATE SCHEMA mdm_admin;
CREATE SCHEMA mdm_internal;

CREATE TABLE mdm_internal.operations (
    operation_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    operation_kind text NOT NULL,
    entity_name pg_catalog.name,
    status text NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    result_code text,
    outcome jsonb NOT NULL DEFAULT '{}'::pg_catalog.jsonb,
    actor_name text NOT NULL,
    actor_role_name text NOT NULL,
    started_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    completed_at timestamptz,
    CHECK ((status = 'running') = (completed_at IS NULL))
);

COMMENT ON TABLE mdm_internal.operations IS
    'Durable: committed MDM operation outcomes; included in logical dumps.';

SELECT pg_catalog.pg_extension_config_dump(
    'mdm_internal.operations'::pg_catalog.regclass,
    ''
);

REVOKE ALL ON SCHEMA mdm_internal FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA mdm_internal FROM PUBLIC;
REVOKE CREATE ON SCHEMA mdm, mdm_out, mdm_steward, mdm_admin FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/integration.rs:128
-- pg_mdm::integration::capability_report_sql
CREATE FUNCTION mdm_internal.integration_capabilities() RETURNS TABLE (capability text, major_version smallint, minor_version smallint, enabled boolean, details jsonb) STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'capability_report_sql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/integration.rs:167
-- pg_mdm::integration::require_graph_v1_sql
CREATE FUNCTION mdm_internal.require_graph_v1() RETURNS jsonb STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'require_graph_v1_sql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/catalog.rs:201
-- pg_mdm::catalog::verify_installation
CREATE FUNCTION mdm_admin.verify_installation() RETURNS text STRICT SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'verify_installation_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/schema.rs:44
-- requires:
--   verify_installation

-- finalize

REVOKE ALL ON FUNCTION mdm_internal.integration_capabilities() FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.require_graph_v1() FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_admin.verify_installation() FROM PUBLIC;
/* </end connected objects> */

