/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/schema.rs:16
-- bootstrap

CREATE SCHEMA mdm;
CREATE SCHEMA mdm_out;
CREATE SCHEMA mdm_steward;
CREATE SCHEMA mdm_admin;
CREATE SCHEMA mdm_internal;

CREATE TYPE mdm_internal.normalized_value AS (
    state text,
    normalized text,
    canonical_bytes bytea
);

CREATE TABLE mdm_internal.operations (
    operation_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    operation_kind text NOT NULL,
    entity_name pg_catalog.name,
    status text NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    result_code text,
    outcome jsonb NOT NULL DEFAULT '{}'::pg_catalog.jsonb,
    actor_name text NOT NULL,
    actor_role_name text NOT NULL,
    started_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    completed_at timestamptz,
    CHECK ((status = 'running') = (completed_at IS NULL))
);

CREATE TABLE mdm_internal.entities (
    entity_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_name pg_catalog.name NOT NULL UNIQUE,
    execution_role_name text NOT NULL,
    desired_version bigint NOT NULL CHECK (desired_version > 0),
    active_version bigint,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    created_by_name text NOT NULL,
    CHECK (active_version IS NULL OR active_version > 0)
);

CREATE TABLE mdm_internal.definitions (
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    definition_version bigint NOT NULL CHECK (definition_version > 0),
    parent_version bigint,
    user_definition jsonb NOT NULL,
    expanded_definition jsonb NOT NULL,
    logical_candidate_plan jsonb NOT NULL,
    semantic_manifest jsonb NOT NULL,
    definition_digest bytea NOT NULL CHECK (octet_length(definition_digest) = 32),
    comment text,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    created_by_name text NOT NULL,
    PRIMARY KEY (entity_id, definition_version),
    CHECK (parent_version IS NULL OR parent_version < definition_version)
);

CREATE TABLE mdm_internal.source_identities (
    source_identity_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    source_name pg_catalog.name NOT NULL,
    relation_name text NOT NULL,
    key_contract jsonb NOT NULL,
    identity_digest bytea NOT NULL CHECK (octet_length(identity_digest) = 32),
    UNIQUE (entity_id, source_name)
);

CREATE TABLE mdm_internal.source_bindings (
    source_identity_id uuid PRIMARY KEY REFERENCES mdm_internal.source_identities(source_identity_id),
    relation_oid oid NOT NULL,
    binding_fingerprint jsonb NOT NULL,
    bound_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp()
);

CREATE TABLE mdm_internal.source_records (
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    source_identity_id uuid NOT NULL
        REFERENCES mdm_internal.source_identities(source_identity_id),
    source_record_key bytea NOT NULL,
    source_record_id uuid NOT NULL DEFAULT pg_catalog.uuidv7(),
    active boolean NOT NULL DEFAULT false,
    first_seen_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    last_seen_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    PRIMARY KEY (entity_id, source_identity_id, source_record_key),
    UNIQUE (source_record_id),
    UNIQUE (entity_id, source_record_id)
);

CREATE TABLE mdm_internal.output_names (
    output_name pg_catalog.name PRIMARY KEY,
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    output_kind text NOT NULL CHECK (output_kind IN ('entity', 'members', 'review')),
    UNIQUE (entity_id, output_kind)
);

CREATE TABLE mdm_internal.execution_role_bindings (
    entity_id uuid PRIMARY KEY REFERENCES mdm_internal.entities(entity_id),
    role_oid oid NOT NULL,
    bound_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp()
);

CREATE TABLE mdm_internal.definition_artifacts (
    artifact_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_id uuid NOT NULL,
    definition_version bigint NOT NULL,
    compiler_version integer NOT NULL CHECK (compiler_version > 0),
    artifact_format_version integer NOT NULL CHECK (artifact_format_version > 0),
    artifact_bytes bytea NOT NULL,
    artifact_digest bytea NOT NULL CHECK (octet_length(artifact_digest) = 32),
    created_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    created_by_name text NOT NULL,
    UNIQUE (entity_id, definition_version, compiler_version, artifact_digest),
    FOREIGN KEY (entity_id, definition_version) REFERENCES mdm_internal.definitions(entity_id, definition_version)
);

COMMENT ON TABLE mdm_internal.operations IS
    'Durable: committed MDM operation outcomes; included in logical dumps.';

SELECT pg_catalog.pg_extension_config_dump(
    'mdm_internal.operations'::pg_catalog.regclass,
    ''
);

SELECT pg_catalog.pg_extension_config_dump('mdm_internal.entities'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.definitions'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.source_identities'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.source_records'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.output_names'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.definition_artifacts'::pg_catalog.regclass, '');

REVOKE ALL ON SCHEMA mdm_internal FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA mdm_internal FROM PUBLIC;
REVOKE CREATE ON SCHEMA mdm, mdm_out, mdm_steward, mdm_admin FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/describe.rs:29
-- pg_mdm::api::describe::describe_entity
CREATE FUNCTION mdm_internal.describe_entity(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'describe_entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/describe.rs:13
-- pg_mdm::api::describe::describe
CREATE FUNCTION mdm.describe(entity_name text, format text DEFAULT 'summary') RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'describe_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:270
-- pg_mdm::api::constructors::entity
CREATE FUNCTION mdm.entity(name text, sources jsonb[], fields jsonb[], matches jsonb[], golden_values jsonb[], preset text DEFAULT NULL, limits jsonb DEFAULT '{}'::jsonb, execution_role text DEFAULT NULL) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:105
-- pg_mdm::api::constructors::field
CREATE FUNCTION mdm.field(name text, type text, cleaner text, cleaner_options jsonb DEFAULT '{}'::jsonb, display text DEFAULT 'masked') RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'field_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:241
-- pg_mdm::api::constructors::golden_value
CREATE FUNCTION mdm.golden_value(field text, policy text, sources text[] DEFAULT NULL) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'golden_value_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/integration.rs:128
-- pg_mdm::integration::capability_report_sql
CREATE FUNCTION mdm_internal.integration_capabilities() RETURNS TABLE (capability text, major_version smallint, minor_version smallint, enabled boolean, details jsonb) STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'capability_report_sql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:171
-- pg_mdm::api::constructors::match_rule
CREATE FUNCTION mdm.match(name text, fields text[], comparison text, strength text, evidence_group text, threshold integer DEFAULT NULL, candidate jsonb DEFAULT NULL) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'match_rule_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/normalization.rs:195
-- pg_mdm::normalization::normalize_date
CREATE FUNCTION mdm_internal.normalize_date(value date, cleaner text DEFAULT 'date', cleaner_version integer DEFAULT 1, source_state text DEFAULT 'present', options jsonb DEFAULT '{}'::jsonb) RETURNS mdm_internal.normalized_value IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'normalize_date_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/normalization.rs:166
-- pg_mdm::normalization::normalize_text
CREATE FUNCTION mdm_internal.normalize_text(value text, cleaner text, cleaner_version integer, source_state text DEFAULT 'present', options jsonb DEFAULT '{}'::jsonb) RETURNS mdm_internal.normalized_value IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'normalize_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/create.rs:430
-- pg_mdm::api::create::persist_entity
CREATE FUNCTION mdm_internal.persist_entity(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'persist_entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/create.rs:48
-- pg_mdm::api::create::create
CREATE FUNCTION mdm.create(definition jsonb, expected_version bigint DEFAULT NULL, comment text DEFAULT NULL) RETURNS TABLE (operation_id uuid, entity_name text, desired_version bigint, changed boolean, definition_digest bytea, artifact_digest bytea) LANGUAGE c AS 'MODULE_PATHNAME', 'create_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/rebind.rs:179
-- pg_mdm::api::rebind::persist_rebind
CREATE FUNCTION mdm_internal.persist_rebind(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'persist_rebind_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/rebind.rs:154
-- pg_mdm::api::rebind::prepare_rebind
CREATE FUNCTION mdm_internal.prepare_rebind(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'prepare_rebind_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/rebind.rs:106
-- pg_mdm::api::rebind::rebind
CREATE FUNCTION mdm_admin.rebind(entity_name text) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'rebind_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/integration.rs:167
-- pg_mdm::integration::require_graph_v1_sql
CREATE FUNCTION mdm_internal.require_graph_v1() RETURNS jsonb STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'require_graph_v1_sql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:32
-- pg_mdm::api::constructors::source
CREATE FUNCTION mdm.source(name text, relation regclass, source_id text[], mode text, fields jsonb, row_changed_at text DEFAULT NULL, soft_delete_when jsonb DEFAULT NULL, authority jsonb DEFAULT '{}'::jsonb) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'source_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/catalog.rs:236
-- pg_mdm::catalog::verify_installation
CREATE FUNCTION mdm_admin.verify_installation() RETURNS text STRICT SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'verify_installation_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/schema.rs:152
-- requires:
--   verify_installation
--   normalize_text
--   normalize_date

-- finalize

REVOKE ALL ON FUNCTION mdm_internal.integration_capabilities() FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.require_graph_v1() FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_admin.verify_installation() FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.persist_entity(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.describe_entity(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.prepare_rebind(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.persist_rebind(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_admin.rebind(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.normalize_text(text, text, integer, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.normalize_date(date, text, integer, text, jsonb) FROM PUBLIC;
/* </end connected objects> */

