/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/schema.rs:28
-- bootstrap

CREATE SCHEMA mdm;
CREATE SCHEMA mdm_out;
CREATE SCHEMA mdm_steward;
CREATE SCHEMA mdm_admin;
CREATE SCHEMA mdm_internal;
CREATE SCHEMA mdm_graph;

CREATE TYPE mdm_internal.normalized_value AS (
    state text,
    normalized text,
    canonical_bytes bytea
);

CREATE TYPE mdm_graph.normalized_value AS (
    state text,
    normalized text,
    canonical_bytes bytea
);

CREATE TABLE mdm_internal.operations (
    operation_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    operation_kind text NOT NULL,
    entity_name pg_catalog.name,
    status text NOT NULL CHECK (status IN ('running', 'succeeded', 'failed')),
    result_code text,
    outcome jsonb NOT NULL DEFAULT '{}'::pg_catalog.jsonb,
    actor_name text NOT NULL,
    actor_role_name text NOT NULL,
    started_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    completed_at timestamptz,
    CHECK ((status = 'running') = (completed_at IS NULL))
);

CREATE TABLE mdm_internal.entities (
    entity_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_name pg_catalog.name NOT NULL UNIQUE,
    execution_role_name text NOT NULL,
    desired_version bigint NOT NULL CHECK (desired_version > 0),
    active_version bigint,
    decision_epoch bigint NOT NULL DEFAULT 0,
    publication_revision bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    created_by_name text NOT NULL,
    CHECK (active_version IS NULL OR active_version > 0),
    CHECK (decision_epoch >= 0),
    CHECK (publication_revision >= 0)
);

CREATE TABLE mdm_internal.definitions (
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    definition_version bigint NOT NULL CHECK (definition_version > 0),
    parent_version bigint,
    user_definition jsonb NOT NULL,
    expanded_definition jsonb NOT NULL,
    logical_candidate_plan jsonb NOT NULL,
    semantic_manifest jsonb NOT NULL,
    definition_digest bytea NOT NULL CHECK (octet_length(definition_digest) = 32),
    comment text,
    created_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    created_by_name text NOT NULL,
    PRIMARY KEY (entity_id, definition_version),
    CHECK (parent_version IS NULL OR parent_version < definition_version)
);

CREATE TABLE mdm_internal.source_identities (
    source_identity_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    source_name pg_catalog.name NOT NULL,
    relation_name text NOT NULL,
    key_contract jsonb NOT NULL,
    identity_digest bytea NOT NULL CHECK (octet_length(identity_digest) = 32),
    UNIQUE (entity_id, source_name)
);

CREATE TABLE mdm_internal.source_bindings (
    source_identity_id uuid PRIMARY KEY REFERENCES mdm_internal.source_identities(source_identity_id),
    relation_oid oid NOT NULL,
    binding_fingerprint jsonb NOT NULL,
    bound_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp()
);

CREATE TABLE mdm_internal.source_records (
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    source_identity_id uuid NOT NULL
        REFERENCES mdm_internal.source_identities(source_identity_id),
    source_record_key bytea NOT NULL,
    source_record_id uuid NOT NULL DEFAULT pg_catalog.uuidv7(),
    active boolean NOT NULL DEFAULT false,
    first_seen_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    last_seen_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    PRIMARY KEY (entity_id, source_identity_id, source_record_key),
    UNIQUE (source_record_id),
    UNIQUE (entity_id, source_record_id)
);

CREATE TABLE mdm_internal.output_names (
    output_name pg_catalog.name PRIMARY KEY,
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    output_kind text NOT NULL CHECK (output_kind IN ('entity', 'members', 'review')),
    UNIQUE (entity_id, output_kind)
);

CREATE TABLE mdm_internal.execution_role_bindings (
    entity_id uuid PRIMARY KEY REFERENCES mdm_internal.entities(entity_id),
    role_oid oid NOT NULL,
    bound_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp()
);

CREATE TABLE mdm_internal.definition_artifacts (
    artifact_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_id uuid NOT NULL,
    definition_version bigint NOT NULL,
    compiler_version integer NOT NULL CHECK (compiler_version > 0),
    artifact_format_version integer NOT NULL CHECK (artifact_format_version > 0),
    artifact_bytes bytea NOT NULL,
    artifact_digest bytea NOT NULL CHECK (octet_length(artifact_digest) = 32),
    created_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    created_by_name text NOT NULL,
    UNIQUE (entity_id, definition_version, compiler_version, artifact_digest),
    FOREIGN KEY (entity_id, definition_version) REFERENCES mdm_internal.definitions(entity_id, definition_version)
);

CREATE TABLE mdm_internal.graph_bindings (
    graph_binding_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    definition_version bigint NOT NULL,
    artifact_id uuid NOT NULL
        REFERENCES mdm_internal.definition_artifacts(artifact_id),
    graph_generation bigint NOT NULL CHECK (graph_generation > 0),
    execution_role_oid oid NOT NULL,
    source_binding_digest bytea NOT NULL
        CHECK (octet_length(source_binding_digest) = 32),
    root_relation_oids oid[] NOT NULL,
    graph_contract_version smallint NOT NULL CHECK (graph_contract_version = 1),
    graph_digest bytea NOT NULL CHECK (octet_length(graph_digest) = 32),
    graph_contract jsonb NOT NULL,
    graph_binding_digest bytea NOT NULL
        CHECK (octet_length(graph_binding_digest) = 32),
    created_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    UNIQUE (entity_id, graph_generation),
    FOREIGN KEY (entity_id, definition_version)
        REFERENCES mdm_internal.definitions(entity_id, definition_version)
);

CREATE TABLE mdm_internal.graph_members (
    graph_binding_id uuid NOT NULL
        REFERENCES mdm_internal.graph_bindings(graph_binding_id),
    logical_id text NOT NULL,
    topological_ordinal integer NOT NULL CHECK (topological_ordinal >= 0),
    relation_oid oid NOT NULL,
    relation_name text NOT NULL,
    contract_generation bigint NOT NULL CHECK (contract_generation > 0),
    contract_digest bytea NOT NULL CHECK (octet_length(contract_digest) = 32),
    contract jsonb NOT NULL,
    PRIMARY KEY (graph_binding_id, logical_id),
    UNIQUE (graph_binding_id, topological_ordinal),
    UNIQUE (relation_oid)
);

CREATE TABLE mdm_internal.steward_decisions (
    decision_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    left_source_record_id uuid NOT NULL,
    right_source_record_id uuid NOT NULL,
    decision text NOT NULL CHECK (decision IN ('MATCH', 'NOT_MATCH')),
    decision_version bigint NOT NULL CHECK (decision_version > 0),
    reason text NOT NULL CHECK (pg_catalog.length(pg_catalog.btrim(reason)) > 0),
    created_by_name text NOT NULL,
    created_as_role_name text NOT NULL,
    operation_id uuid NOT NULL REFERENCES mdm_internal.operations(operation_id),
    base_publication_revision bigint NOT NULL CHECK (base_publication_revision >= 0),
    decision_epoch bigint NOT NULL CHECK (decision_epoch > 0),
    created_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    supersedes uuid UNIQUE,
    is_current boolean NOT NULL DEFAULT true,
    CHECK (left_source_record_id <> right_source_record_id),
    CHECK (supersedes IS NULL OR supersedes <> decision_id),
    UNIQUE (entity_id, left_source_record_id, right_source_record_id, decision_version),
    FOREIGN KEY (entity_id, left_source_record_id)
        REFERENCES mdm_internal.source_records(entity_id, source_record_id),
    FOREIGN KEY (entity_id, right_source_record_id)
        REFERENCES mdm_internal.source_records(entity_id, source_record_id)
);

CREATE UNIQUE INDEX steward_decisions_one_current_pair
    ON mdm_internal.steward_decisions (
        entity_id, left_source_record_id, right_source_record_id
    ) WHERE is_current;

CREATE OR REPLACE FUNCTION mdm_internal.validate_steward_decision_chain()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO pg_catalog, mdm_internal, pg_temp
AS $function$
DECLARE
    predecessor mdm_internal.steward_decisions%ROWTYPE;
    has_successor boolean;
    current_state boolean;
BEGIN
    IF NEW.supersedes IS NOT NULL THEN
        SELECT * INTO predecessor
        FROM mdm_internal.steward_decisions
        WHERE decision_id = NEW.supersedes;
        IF NOT FOUND
           OR predecessor.entity_id <> NEW.entity_id
           OR predecessor.left_source_record_id <> NEW.left_source_record_id
           OR predecessor.right_source_record_id <> NEW.right_source_record_id
           OR predecessor.decision_version + 1 <> NEW.decision_version
           OR predecessor.is_current THEN
            RAISE EXCEPTION 'invalid steward decision predecessor';
        END IF;
    END IF;
    SELECT EXISTS (
        SELECT 1 FROM mdm_internal.steward_decisions
        WHERE supersedes = NEW.decision_id
    ) INTO has_successor;
    SELECT is_current INTO current_state
    FROM mdm_internal.steward_decisions
    WHERE decision_id = NEW.decision_id;
    IF NOT FOUND OR current_state = has_successor THEN
        RAISE EXCEPTION 'steward decision current state does not match its successor';
    END IF;
    RETURN NEW;
END
$function$;

CREATE CONSTRAINT TRIGGER steward_decisions_chain_check
AFTER INSERT OR UPDATE ON mdm_internal.steward_decisions
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION mdm_internal.validate_steward_decision_chain();

CREATE TABLE mdm_internal.publications (
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    publication_revision bigint NOT NULL CHECK (publication_revision > 0),
    definition_version bigint NOT NULL,
    decision_epoch bigint NOT NULL,
    operation_id uuid NOT NULL REFERENCES mdm_internal.operations(operation_id),
    result_digest bytea NOT NULL CHECK (octet_length(result_digest) = 32),
    published_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    PRIMARY KEY (entity_id, publication_revision),
    FOREIGN KEY (entity_id, definition_version)
        REFERENCES mdm_internal.definitions(entity_id, definition_version)
);

CREATE TABLE mdm_internal.publication_observations (
    observation_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_id uuid NOT NULL,
    publication_revision bigint NOT NULL,
    decision_epoch bigint NOT NULL CHECK (decision_epoch >= 0),
    artifact_id uuid NOT NULL REFERENCES mdm_internal.definition_artifacts(artifact_id),
    operation_id uuid NOT NULL REFERENCES mdm_internal.operations(operation_id),
    source_boundary jsonb NOT NULL,
    source_boundary_digest bytea NOT NULL CHECK (octet_length(source_boundary_digest) = 32),
    observed_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    FOREIGN KEY (entity_id, publication_revision)
        REFERENCES mdm_internal.publications(entity_id, publication_revision)
);

CREATE TABLE mdm_internal.identity_registry (
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    mdm_id uuid NOT NULL DEFAULT pg_catalog.uuidv7(),
    created_revision bigint NOT NULL,
    retired_revision bigint,
    status text NOT NULL CHECK (status IN ('active', 'merged', 'split', 'retired')),
    PRIMARY KEY (entity_id, mdm_id),
    CHECK (retired_revision IS NULL OR retired_revision >= created_revision),
    CHECK ((status = 'active') = (retired_revision IS NULL))
);

CREATE TABLE mdm_internal.memberships (
    entity_id uuid NOT NULL,
    source_record_id uuid NOT NULL,
    source_name name NOT NULL,
    source_id jsonb NOT NULL,
    mdm_id uuid NOT NULL,
    active boolean NOT NULL,
    first_membership_revision bigint NOT NULL,
    last_membership_revision bigint NOT NULL,
    membership_reason text NOT NULL,
    last_change_revision bigint NOT NULL,
    PRIMARY KEY (entity_id, source_record_id),
    FOREIGN KEY (entity_id, source_record_id)
        REFERENCES mdm_internal.source_records(entity_id, source_record_id),
    FOREIGN KEY (entity_id, mdm_id)
        REFERENCES mdm_internal.identity_registry(entity_id, mdm_id),
    CHECK (last_membership_revision >= first_membership_revision)
);

CREATE TABLE mdm_internal.identity_aliases (
    entity_id uuid NOT NULL,
    alias_mdm_id uuid NOT NULL,
    canonical_mdm_id uuid NOT NULL,
    publication_revision bigint NOT NULL,
    PRIMARY KEY (entity_id, alias_mdm_id),
    FOREIGN KEY (entity_id, alias_mdm_id)
        REFERENCES mdm_internal.identity_registry(entity_id, mdm_id),
    FOREIGN KEY (entity_id, canonical_mdm_id)
        REFERENCES mdm_internal.identity_registry(entity_id, mdm_id),
    CHECK (alias_mdm_id <> canonical_mdm_id)
);

CREATE TABLE mdm_internal.identity_splits (
    entity_id uuid NOT NULL,
    parent_mdm_id uuid NOT NULL,
    child_mdm_id uuid NOT NULL,
    publication_revision bigint NOT NULL,
    PRIMARY KEY (entity_id, parent_mdm_id, child_mdm_id, publication_revision),
    FOREIGN KEY (entity_id, parent_mdm_id)
        REFERENCES mdm_internal.identity_registry(entity_id, mdm_id),
    FOREIGN KEY (entity_id, child_mdm_id)
        REFERENCES mdm_internal.identity_registry(entity_id, mdm_id)
);

CREATE TABLE mdm_internal.output_fields (
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    field_name name NOT NULL,
    field_ordinal smallint NOT NULL CHECK (field_ordinal > 0),
    field_type_name text NOT NULL,
    created_definition_version bigint NOT NULL,
    PRIMARY KEY (entity_id, field_name),
    UNIQUE (entity_id, field_ordinal)
);

CREATE TABLE mdm_internal.golden_provenance (
    entity_id uuid NOT NULL,
    publication_revision bigint NOT NULL,
    mdm_id uuid NOT NULL,
    field_name name NOT NULL,
    value jsonb,
    normalized_value text,
    status text NOT NULL CHECK (status IN ('selected', 'override', 'override_conflict', 'no_value')),
    winning_source_record_id uuid,
    policy text NOT NULL,
    policy_version smallint NOT NULL,
    tie_break text NOT NULL,
    contributors jsonb NOT NULL,
    definition_version bigint NOT NULL,
    PRIMARY KEY (entity_id, publication_revision, mdm_id, field_name),
    FOREIGN KEY (entity_id, publication_revision)
        REFERENCES mdm_internal.publications(entity_id, publication_revision),
    FOREIGN KEY (entity_id, mdm_id)
        REFERENCES mdm_internal.identity_registry(entity_id, mdm_id)
);

CREATE TABLE mdm_internal.reviews (
    review_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    issue_key bytea NOT NULL CHECK (octet_length(issue_key) = 32),
    occurrence integer NOT NULL CHECK (occurrence > 0),
    status text NOT NULL CHECK (status IN ('open', 'resolved')),
    severity text NOT NULL,
    reason_code text NOT NULL,
    subjects jsonb NOT NULL,
    masked_summary jsonb NOT NULL,
    opened_revision bigint NOT NULL,
    resolved_revision bigint,
    last_change_revision bigint NOT NULL,
    concurrency_version bigint NOT NULL DEFAULT 1,
    UNIQUE (entity_id, issue_key, occurrence),
    CHECK ((status = 'resolved') = (resolved_revision IS NOT NULL))
);

CREATE TABLE mdm_internal.resolution_facts (
    entity_id uuid NOT NULL,
    publication_revision bigint NOT NULL,
    fact_number bigint NOT NULL,
    subject_kind text NOT NULL,
    subject_key bytea NOT NULL,
    fact_kind text NOT NULL,
    fact jsonb NOT NULL,
    PRIMARY KEY (entity_id, publication_revision, fact_number),
    FOREIGN KEY (entity_id, publication_revision)
        REFERENCES mdm_internal.publications(entity_id, publication_revision)
);

CREATE TABLE mdm_internal.golden_override_directives (
    override_id uuid PRIMARY KEY DEFAULT pg_catalog.uuidv7(),
    entity_id uuid NOT NULL REFERENCES mdm_internal.entities(entity_id),
    field_name name NOT NULL,
    anchor_source_record_id uuid NOT NULL,
    action text NOT NULL CHECK (action IN ('SET', 'CLEAR')),
    value jsonb,
    value_type_name text,
    override_version bigint NOT NULL CHECK (override_version > 0),
    reason text NOT NULL CHECK (pg_catalog.length(pg_catalog.btrim(reason)) > 0),
    created_by_name text NOT NULL,
    created_as_role_name text NOT NULL,
    operation_id uuid NOT NULL REFERENCES mdm_internal.operations(operation_id),
    base_publication_revision bigint NOT NULL CHECK (base_publication_revision >= 0),
    decision_epoch bigint NOT NULL CHECK (decision_epoch > 0),
    created_at timestamptz NOT NULL DEFAULT pg_catalog.statement_timestamp(),
    supersedes uuid UNIQUE,
    is_current boolean NOT NULL DEFAULT true,
    UNIQUE (entity_id, field_name, anchor_source_record_id, override_version),
    FOREIGN KEY (entity_id, anchor_source_record_id)
        REFERENCES mdm_internal.source_records(entity_id, source_record_id),
    CHECK (
        (action = 'SET' AND value IS NOT NULL AND value <> 'null'::jsonb AND value_type_name IS NOT NULL)
        OR (action = 'CLEAR' AND value IS NULL AND value_type_name IS NULL)
    )
);

CREATE UNIQUE INDEX golden_overrides_one_current_anchor
    ON mdm_internal.golden_override_directives (entity_id, field_name, anchor_source_record_id)
    WHERE is_current;

CREATE OR REPLACE FUNCTION mdm_internal.validate_golden_override_chain()
RETURNS trigger
LANGUAGE plpgsql
SET search_path TO pg_catalog, mdm_internal, pg_temp
AS $function$
DECLARE predecessor mdm_internal.golden_override_directives%ROWTYPE;
DECLARE has_successor boolean;
DECLARE current_state boolean;
BEGIN
    IF NEW.supersedes IS NOT NULL THEN
        SELECT * INTO predecessor FROM mdm_internal.golden_override_directives
         WHERE override_id = NEW.supersedes;
        IF NOT FOUND OR predecessor.entity_id <> NEW.entity_id
           OR predecessor.field_name <> NEW.field_name
           OR predecessor.anchor_source_record_id <> NEW.anchor_source_record_id
           OR predecessor.override_version + 1 <> NEW.override_version
           OR predecessor.is_current THEN
            RAISE EXCEPTION 'invalid golden override predecessor';
        END IF;
    END IF;
    SELECT EXISTS (SELECT 1 FROM mdm_internal.golden_override_directives WHERE supersedes = NEW.override_id)
      INTO has_successor;
    SELECT is_current INTO current_state FROM mdm_internal.golden_override_directives WHERE override_id = NEW.override_id;
    IF NOT FOUND OR current_state = has_successor THEN
        RAISE EXCEPTION 'golden override current state does not match its successor';
    END IF;
    RETURN NEW;
END
$function$;

CREATE CONSTRAINT TRIGGER golden_override_chain_check
AFTER INSERT OR UPDATE ON mdm_internal.golden_override_directives
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION mdm_internal.validate_golden_override_chain();

CREATE TABLE mdm_graph.source_identity_map (
    entity_id uuid NOT NULL,
    entity_name text NOT NULL,
    source_identity_id uuid NOT NULL,
    source_name text NOT NULL,
    PRIMARY KEY (entity_id, source_name)
);

CREATE TABLE mdm_graph.source_records (
    entity_id uuid NOT NULL,
    source_identity_id uuid NOT NULL,
    source_record_key bytea NOT NULL,
    source_record_id uuid PRIMARY KEY,
    active boolean NOT NULL
);

CREATE TABLE mdm_graph.definition_limits (
    entity_id uuid PRIMARY KEY,
    entity_name text NOT NULL,
    expanded_definition jsonb NOT NULL
);

CREATE FUNCTION mdm_graph.normalize_text(value text, cleaner text, cleaner_version integer, source_state text DEFAULT 'present', options jsonb DEFAULT '{}'::jsonb)
RETURNS mdm_graph.normalized_value
LANGUAGE sql IMMUTABLE PARALLEL SAFE SECURITY DEFINER
SET search_path TO pg_catalog, mdm_internal, pg_temp
AS $graph$ SELECT ROW((n).state, (n).normalized, (n).canonical_bytes)::mdm_graph.normalized_value
FROM (SELECT mdm_internal.normalize_text($1, $2, $3, $4, $5) AS n) s $graph$;

CREATE FUNCTION mdm_graph.normalize_date(value date, cleaner text DEFAULT 'date', cleaner_version integer DEFAULT 1, source_state text DEFAULT 'present', options jsonb DEFAULT '{}'::jsonb)
RETURNS mdm_graph.normalized_value
LANGUAGE sql IMMUTABLE PARALLEL SAFE SECURITY DEFINER
SET search_path TO pg_catalog, mdm_internal, pg_temp
AS $graph$ SELECT ROW((n).state, (n).normalized, (n).canonical_bytes)::mdm_graph.normalized_value
FROM (SELECT mdm_internal.normalize_date($1, $2, $3, $4, $5) AS n) s $graph$;

CREATE FUNCTION mdm_graph.normalized_levenshtein_score(left_value text, right_value text, max_work bigint)
RETURNS integer
LANGUAGE sql IMMUTABLE PARALLEL SAFE SECURITY DEFINER
SET search_path TO pg_catalog, mdm_internal, pg_temp
AS $graph$ SELECT mdm_internal.normalized_levenshtein_score($1, $2, $3) $graph$;

CREATE FUNCTION mdm_graph.evidence_digest(value text)
RETURNS bytea
LANGUAGE sql IMMUTABLE PARALLEL SAFE SECURITY DEFINER
SET search_path TO pg_catalog, mdm_internal, pg_temp
AS $graph$ SELECT mdm_internal.evidence_digest($1) $graph$;

COMMENT ON TABLE mdm_internal.operations IS
    'Durable: committed MDM operation outcomes; included in logical dumps.';

SELECT pg_catalog.pg_extension_config_dump(
    'mdm_internal.operations'::pg_catalog.regclass,
    ''
);

SELECT pg_catalog.pg_extension_config_dump('mdm_internal.entities'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.definitions'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.source_identities'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.source_records'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.output_names'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.definition_artifacts'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.steward_decisions'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.publications'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.publication_observations'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.identity_registry'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.memberships'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.identity_aliases'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.identity_splits'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.output_fields'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.golden_provenance'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.reviews'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.resolution_facts'::pg_catalog.regclass, '');
SELECT pg_catalog.pg_extension_config_dump('mdm_internal.golden_override_directives'::pg_catalog.regclass, '');

REVOKE ALL ON SCHEMA mdm_internal FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA mdm_internal FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.validate_golden_override_chain() FROM PUBLIC;
REVOKE CREATE ON SCHEMA mdm, mdm_out, mdm_steward, mdm_admin, mdm_graph FROM PUBLIC;
REVOKE ALL ON SCHEMA mdm_graph FROM PUBLIC;
REVOKE ALL ON TABLE mdm_internal.graph_bindings, mdm_internal.graph_members FROM PUBLIC;
REVOKE ALL ON TABLE mdm_graph.source_identity_map, mdm_graph.source_records, mdm_graph.definition_limits FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_graph.normalize_text(text, text, integer, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_graph.normalize_date(date, text, integer, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_graph.normalized_levenshtein_score(text, text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_graph.evidence_digest(text) FROM PUBLIC;
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/describe.rs:151
-- pg_mdm::api::describe::describe_entity
CREATE FUNCTION mdm_internal.describe_entity(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'describe_entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/describe.rs:135
-- pg_mdm::api::describe::describe
CREATE FUNCTION mdm.describe(entity_name text, format text DEFAULT 'summary') RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'describe_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:276
-- pg_mdm::api::constructors::entity
CREATE FUNCTION mdm.entity(name text, sources jsonb[], fields jsonb[], matches jsonb[], golden_values jsonb[], preset text DEFAULT NULL, limits jsonb DEFAULT '{}'::jsonb, execution_role text DEFAULT NULL) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/evidence.rs:56
-- pg_mdm::evidence::evidence_digest
CREATE FUNCTION mdm_internal.evidence_digest(value text) RETURNS bytea IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'evidence_digest_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/explain.rs:83
-- pg_mdm::api::explain::explain_entity
CREATE FUNCTION mdm_internal.explain_entity(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'explain_entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/explain.rs:60
-- pg_mdm::api::explain::explain
CREATE FUNCTION mdm.explain(entity_name text, subject jsonb, publication_revision bigint DEFAULT NULL, max_facts integer DEFAULT 100) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'explain_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:105
-- pg_mdm::api::constructors::field
CREATE FUNCTION mdm.field(name text, type text, cleaner text, cleaner_options jsonb DEFAULT '{}'::jsonb, display text DEFAULT 'masked') RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'field_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:247
-- pg_mdm::api::constructors::golden_value
CREATE FUNCTION mdm.golden_value(field text, policy text, sources text[] DEFAULT NULL) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'golden_value_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/integration.rs:128
-- pg_mdm::integration::capability_report_sql
CREATE FUNCTION mdm_internal.integration_capabilities() RETURNS TABLE (capability text, major_version smallint, minor_version smallint, enabled boolean, details jsonb) STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'capability_report_sql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:171
-- pg_mdm::api::constructors::match_rule
CREATE FUNCTION mdm.match(name text, fields text[], comparison text, strength text, evidence_group text, threshold integer DEFAULT NULL, candidate jsonb DEFAULT NULL) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'match_rule_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/normalization.rs:195
-- pg_mdm::normalization::normalize_date
CREATE FUNCTION mdm_internal.normalize_date(value date, cleaner text DEFAULT 'date', cleaner_version integer DEFAULT 1, source_state text DEFAULT 'present', options jsonb DEFAULT '{}'::jsonb) RETURNS mdm_internal.normalized_value IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'normalize_date_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/normalization.rs:166
-- pg_mdm::normalization::normalize_text
CREATE FUNCTION mdm_internal.normalize_text(value text, cleaner text, cleaner_version integer, source_state text DEFAULT 'present', options jsonb DEFAULT '{}'::jsonb) RETURNS mdm_internal.normalized_value IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'normalize_text_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/comparators/levenshtein.rs:80
-- pg_mdm::comparators::levenshtein::normalized_levenshtein_score
CREATE FUNCTION mdm_internal.normalized_levenshtein_score(left_value text, right_value text, max_work bigint) RETURNS integer IMMUTABLE PARALLEL SAFE SET search_path = pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'normalized_levenshtein_score_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/steward.rs:128
-- pg_mdm::api::steward::persist_decision
CREATE FUNCTION mdm_internal.persist_decision(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'persist_decision_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/steward.rs:80
-- pg_mdm::api::steward::decide
CREATE FUNCTION mdm_steward.decide(entity_name text, left_source_record_id uuid, right_source_record_id uuid, decision text, expected_version bigint, reason text) RETURNS TABLE (operation_id uuid, decision_id uuid, decision_version bigint, decision_epoch bigint) LANGUAGE c AS 'MODULE_PATHNAME', 'decide_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/lifecycle.rs:30
-- pg_mdm::api::lifecycle::persist_drop_entity
CREATE FUNCTION mdm_internal.persist_drop_entity(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'persist_drop_entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/lifecycle.rs:14
-- pg_mdm::api::lifecycle::drop_entity
CREATE FUNCTION mdm_admin.drop_entity(entity_name text, confirm text) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'drop_entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/create.rs:852
-- pg_mdm::api::create::persist_entity
CREATE FUNCTION mdm_internal.persist_entity(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'persist_entity_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/create.rs:52
-- pg_mdm::api::create::create
CREATE FUNCTION mdm.create(definition jsonb, expected_version bigint DEFAULT NULL, comment text DEFAULT NULL) RETURNS TABLE (operation_id uuid, entity_name text, desired_version bigint, changed boolean, definition_digest bytea, artifact_digest bytea) LANGUAGE c AS 'MODULE_PATHNAME', 'create_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/steward.rs:464
-- pg_mdm::api::steward::persist_golden_override
CREATE FUNCTION mdm_internal.persist_golden_override(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'persist_golden_override_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/steward.rs:379
-- pg_mdm::api::steward::override_golden
CREATE FUNCTION mdm_steward.override_golden(entity_name text, anchor_source_record_id uuid, field_name text, value jsonb, expected_version bigint, reason text) RETURNS TABLE (operation_id uuid, override_id uuid, override_version bigint, decision_epoch bigint) LANGUAGE c AS 'MODULE_PATHNAME', 'override_golden_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/steward.rs:422
-- pg_mdm::api::steward::clear_golden_override
CREATE FUNCTION mdm_steward.clear_golden_override(entity_name text, anchor_source_record_id uuid, field_name text, expected_version bigint, reason text) RETURNS TABLE (operation_id uuid, override_id uuid, override_version bigint, decision_epoch bigint) LANGUAGE c AS 'MODULE_PATHNAME', 'clear_golden_override_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/rebind.rs:179
-- pg_mdm::api::rebind::persist_rebind
CREATE FUNCTION mdm_internal.persist_rebind(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'persist_rebind_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/rebind.rs:154
-- pg_mdm::api::rebind::prepare_rebind
CREATE FUNCTION mdm_internal.prepare_rebind(request internal) RETURNS jsonb SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'prepare_rebind_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/rebind.rs:106
-- pg_mdm::api::rebind::rebind
CREATE FUNCTION mdm_admin.rebind(entity_name text) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'rebind_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/integration.rs:167
-- pg_mdm::integration::require_graph_v1_sql
CREATE FUNCTION mdm_internal.require_graph_v1() RETURNS jsonb STRICT LANGUAGE c AS 'MODULE_PATHNAME', 'require_graph_v1_sql_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/api/constructors.rs:32
-- pg_mdm::api::constructors::source
CREATE FUNCTION mdm.source(name text, relation regclass, source_id text[], mode text, fields jsonb, row_changed_at text DEFAULT NULL, soft_delete_when jsonb DEFAULT NULL, authority jsonb DEFAULT '{}'::jsonb) RETURNS jsonb LANGUAGE c AS 'MODULE_PATHNAME', 'source_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/catalog.rs:246
-- pg_mdm::catalog::verify_installation
CREATE FUNCTION mdm_admin.verify_installation() RETURNS text STRICT SECURITY DEFINER SET search_path TO pg_catalog, mdm_internal, pg_temp LANGUAGE c AS 'MODULE_PATHNAME', 'verify_installation_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/schema.rs:562
-- requires:
--   verify_installation
--   normalize_text
--   normalize_date

-- finalize

REVOKE ALL ON FUNCTION mdm_internal.integration_capabilities() FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.require_graph_v1() FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_admin.verify_installation() FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.persist_entity(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.describe_entity(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.explain_entity(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.prepare_rebind(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.persist_rebind(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_admin.rebind(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_admin.drop_entity(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.normalize_text(text, text, integer, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.normalize_date(date, text, integer, text, jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.normalized_levenshtein_score(text, text, bigint) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.evidence_digest(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.validate_steward_decision_chain() FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.persist_decision(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.persist_golden_override(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_internal.persist_drop_entity(internal) FROM PUBLIC;
REVOKE ALL ON FUNCTION mdm_steward.decide(text, uuid, uuid, text, bigint, text) FROM PUBLIC;
/* </end connected objects> */

